## Python Lists

In [1]:
bikes = ["kawasaki", "honda", "aprillia", "bajaj"]

In [2]:
for i in bikes:
    print(i)

kawasaki
honda
aprillia
bajaj


### Appending values to a list

In [3]:
bikes.append("hero")
print(bikes)

['kawasaki', 'honda', 'aprillia', 'bajaj', 'hero']


### Using extend method to add values

In [4]:
bikes.extend(["TVS","Ather"])
print(bikes)

['kawasaki', 'honda', 'aprillia', 'bajaj', 'hero', 'TVS', 'Ather']


In [5]:
#list slicing
bikes[1:-1]

['honda', 'aprillia', 'bajaj', 'hero', 'TVS']

## Numpy Arrays

In [6]:
import numpy as np

### Converting list into array using Numpy

In [7]:
np_bikes = np.array(bikes)
np_bikes.sort()
type(np_bikes)

numpy.ndarray

In [8]:
np_cars = np.array(["ford", "toyota", "Tata", "Hyundai", "Porsche", "Kia", "Ferrari"])
np_cars.sort()

### Appending two arrays

In [9]:
np_vehicles = np.append(np_bikes, np_cars, axis=0)
print(np_vehicles)
print("Shape of appended array :", np_vehicles.shape)

['Ather' 'TVS' 'aprillia' 'bajaj' 'hero' 'honda' 'kawasaki' 'Ferrari'
 'Hyundai' 'Kia' 'Porsche' 'Tata' 'ford' 'toyota']
Shape of appended array : (14,)


In [10]:
np_rand = np.random.randint(0, 20, (4,4))
print(np_rand)

[[10  0  3 19]
 [13  5  7 15]
 [19 19  8  2]
 [ 5 17  6 12]]


### Array indexing

In [28]:
a = np.array([[12, 7, 9, 1], [8, 3, 0, 2]])
print("Element at index a[0,1]:", a[0,1])

Element at index a[0,1]: 7


### Array slicing

In [30]:
b = np.array([1, 2, 3, 4, 5, 6, 7])
print(b[1:5])

[2 3 4 5]


In [34]:
c = np.array([[1, 2, 3, 4],[3, 2, 1, 7]])
print(c[1, 1:4])
print(c[0:2, 3])

[2 1 7]
[4 7]


In [22]:
#filling a 4x2 array with random integers in the range 1 to 5
np_num = np.random.randint(1, 5, (4, 2))
print(np_num)
print(np_num.shape)

[[1 3]
 [3 1]
 [1 2]
 [1 2]]
(4, 2)


In [23]:
np_com = np.append(np_rand, np_num, axis=1)
print(np_com) 

[[10  0  3 19  1  3]
 [13  5  7 15  3  1]
 [19 19  8  2  1  2]
 [ 5 17  6 12  1  2]]


In [24]:
#array with defined data type
arr = np.array([[2, 3, 6, 2], [8, 5, 4, 1], [10, 2, 32, 2], [3, 43, 9, 2]], dtype='int32')
print(arr)
print(arr.dtype)

[[ 2  3  6  2]
 [ 8  5  4  1]
 [10  2 32  2]
 [ 3 43  9  2]]
int32


In [25]:
arr = np.append(arr, [[12, 4, 9, 15], [68, 3, 0, 2]], axis=0)
print(arr)

[[ 2  3  6  2]
 [ 8  5  4  1]
 [10  2 32  2]
 [ 3 43  9  2]
 [12  4  9 15]
 [68  3  0  2]]


In [26]:
arr_new = np.append(arr, [[21, 7], [-2, 4], [21, 8], [3, 6], [2, 5], [11, 23]], axis=1)
print(arr_new)
print(arr_new.shape)

[[ 2  3  6  2 21  7]
 [ 8  5  4  1 -2  4]
 [10  2 32  2 21  8]
 [ 3 43  9  2  3  6]
 [12  4  9 15  2  5]
 [68  3  0  2 11 23]]
(6, 6)


In [27]:
#normalising an array
arr_new_max = arr_new.max()
arr_new_min = arr_new.min()
arr_new_norm = (arr_new - arr_new_min)/(arr_new_max - arr_new_min)
print("Normalized array = \n", arr_new_norm)

Normalized array = 
 [[0.05714286 0.07142857 0.11428571 0.05714286 0.32857143 0.12857143]
 [0.14285714 0.1        0.08571429 0.04285714 0.         0.08571429]
 [0.17142857 0.05714286 0.48571429 0.05714286 0.32857143 0.14285714]
 [0.07142857 0.64285714 0.15714286 0.05714286 0.07142857 0.11428571]
 [0.2        0.08571429 0.15714286 0.24285714 0.05714286 0.1       ]
 [1.         0.07142857 0.02857143 0.05714286 0.18571429 0.35714286]]


### Nested Arrays

In [17]:
arr_nested = np.array([[[4, 2, 5], [3 ,7, 2]], [[4, 9, 11], [8, 4, 21]]])
print(arr_nested)
print("Shape of the nested array :", arr_nested.shape)

[[[ 4  2  5]
  [ 3  7  2]]

 [[ 4  9 11]
  [ 8  4 21]]]
Shape of the nested array : (2, 2, 3)


### Creating arrays from scratch

In [18]:
#integer array filled with zeros
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
#floating-point array filled with ones
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#array filled with specific values
np.full((4,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])